Repository AurelicButter/Myneworm, pull requests merged in 2023-03, with the labels that each got.

#59 [Fix/777] Fixed Display Issue with Dates in DatePicker
  src/app/shared/datepicker-modal/datepicker-modal.component.ts
Labels: Bug/Issue

#60 Beta Release 0.6.3
  package-lock.json
  package.json
  src/app/services/utilities.service.ts
  src/app/shared/datepicker-modal/datepicker-modal.component.ts
Labels: Bug/Issue

#61 [Spike/786] Removed Google Fonts from the Site
  angular.json
  src/assets/fonts/roboto-LICENSE
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.eot
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.svg
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.ttf
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.woff
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.woff2
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.eot
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.svg
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.ttf
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.woff
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.woff2
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.eot
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.svg
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.ttf
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.woff
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.woff2
  src/font-faces.css
  src/index.html
Labels: Bug/Issue

#62 Beta Release 0.6.4
  angular.json
  src/assets/fonts/roboto-LICENSE
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.eot
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.svg
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.ttf
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.woff
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.woff2
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.eot
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.svg
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.ttf
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.woff
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.woff2
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.eot
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.svg
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.ttf
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.woff
  src/assets/fonts/roboto/roboto-v30-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.woff2
  src/font-faces.css
  src/index.html
Labels: Bug/Issue

#64 fix(privacy-page): metadata
  src/app/privacy-page/privacy-page.component.ts
Labels: Bug/Issue

#65 [Fix/766] Added New Classes to Schedule Tags and Updated CSS
  src/app/home-page/home-page.component.ts
  src/app/imprint-page/imprint-page.component.ts
  src/app/shared/calendar-styles.css
Labels: Bug/Issue

#66 Beta Release 0.7.0
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.module.ts
  src/app/home-page/home-page.component.ts
  src/app/imprint-page/imprint-page.component.ts
  src/app/privacy-page/privacy-page.component.css
  src/app/privacy-page/privacy-page.component.html
  src/app/privacy-page/privacy-page.component.spec.ts
  src/app/privacy-page/privacy-page.component.ts
  src/app/shared/calendar-styles.css
Labels: Bug/Issue, Documentation, Enhancement

#67 [Feature/793] Added Database Guidelines Page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/database-guidelines/database-guidelines.component.css
  src/app/database-guidelines/database-guidelines.component.html
  src/app/database-guidelines/database-guidelines.component.spec.ts
  src/app/database-guidelines/database-guidelines.component.ts
  src/app/faq-page/faqData.ts
Labels: Documentation, Enhancement

#68 [Feature/797] Updated Navigation Bar CSS to Handle Dropdown Menus
  src/app/app.component.css
  src/app/app.component.html
  src/app/search-bar/search-bar.component.css
Labels: Enhancement
